swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: smtp
    auth_mode: login
    port: 465
    host: smtp.gmail.com
    username: adjagarail@gmail.com
    password: koenigsegg